export const SPLITUP_CATEGORY = {
  ADDITION_AND_SUBTRACTION: "ADDITION_AND_SUBTRACTION",
  MULTIPLICATION: "MULTIPLICATION",
  DIVISION: "DIVISION",
};

export const ROLES = {
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
};

export const EXAM_TYPES = {
  PRACTICE: "PRACTICE",
  SELF_TEST: "SELF_TEST",
  ASSESSMENT: "ASSESSMENT",
  WCL: "WCL",
  ACL: "ACL",
};
